name: signapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.1
  bloc:
  equatable:
  flutter_bloc:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  flutterfire_ui:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

 

flutter:
  uses-material-design: true

